### ISSUE TITLE
Error when upgrading letsPlot to 4.5.2

### ISSUE THREAD

**Issue by changhexuefei** [JetBrains/lets-plot-skia#26]
Hello, after I upgraded the version of letsPlot to 4.5.2, the program showed the following error.

![image](https://github.com/user-attachments/assets/b4a9f0e2-a5fb-4e16-9996-e8a2f0993aa8)

![image](https://github.com/user-attachments/assets/d8b33e79-747e-4baf-ab60-2b0b03c1149f)

Exception in thread "main" java.lang.NoSuchMethodError: 'org.jetbrains.letsPlot.core.util.MonolithicCommon$PlotsBuildResult org.jetbrains.letsPlot.core.util.MonolithicCommon.buildPlotsFromProcessedSpecs$default(org.jetbrains.letsPlot.core.util.MonolithicCommon, java.util.Map, org.jetbrains.letsPlot.commons.geometry.DoubleVector, java.lang.Double, java.lang.Double, int, java.lang.Object)'

**Comment by changhexuefei** [comment]
![image](https://github.com/user-attachments/assets/41cb19ea-bdb4-4c43-94a1-4ac7cd60e404)

**Comment by IKupriyanov-HORIS** [comment]
Released [v2.1.1](https://github.com/JetBrains/lets-plot-skia/releases/tag/v2.1.1) which supports Lets-Plot `4.5.2` and Lets-Plot Kotlin `4.9.3`.
